### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by eingenito** [filecoin-project/filecoin-http-api#4]
- [x]  Make a go module that can be imported into go-filecoin
- [x]  Make an HTTP endpoint that go filecoin can launch on startup that returns something
- [x]  Make the "something" be output from the daemon
- [x]  Create handler registration functionality for given endpoints
- [ ]  Create endpoint to list endpoints available for handler registration ?
- [x]  Make API versioning in the URI
- [x]  Make it HTTPS optional - fake cert (may need to be allowed by server)
- [x]  Make it HTTPS optional - and take a real cert in a directory on the filesystem somewhere
- [x]  Pass in the path to the certs to the server from the calling code
- [x]  Register a callback to implement a "node ID" endpoint
- [x]  Write a test that calls the endpoint
- [ ]  Implement signed message POST endpoint
- [ ]  Implement wait for mined message GET endpoint 
- [ ]  Show to the <-> Alex
- [ ]  Make HTTPS Only
- [ ]  Implement simple 'bearer auth' scheme for auth. Allow integrating code to pass in token via file path
- [ ]  Write proper integration test for go-filecoin
- [ ]  Implement CLI command that calls endpoint and returns result CLI lib option
- [ ]  Mock server endpoint
